name: Fs2 Rabbit
baseurl: /fs2-rabbit
description: Stream-based client for RabbitMQ built on top of Fs2
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.4-SNAPSHOT
org: Fs2 Rabbit
markdown: kramdown
